version: '3.9'
services:
  nestjs_app:
    container_name: nestjs_crud_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - nestjs_db

  nestjs_db:
    container_name: nestjs_crud_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
